version: '3'
services:
    app:
      container_name: aps-final
      restart: always
      build: .
      ports:
        - '3001:80'

      links:
        - database
    database:
      container_name: mongo
      image: mongo
      ports:
        - '27017:27017'
      
        



    
 

